// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psozpuxbyiukufhkpnbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzb3pwdXhieWl1a3VmaGtwbmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTU2ODIsImV4cCI6MjA3MzIzMTY4Mn0.mK9HuhIjIozbHXYGNqAWF8fnV6C9HkT05YArvuAP8Ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});